#CSDH-83 implement image upload
NikolaVetnic/VVF_Back pull request #10
Opened 2022-07-21 19:00 UTC by NikolaVetnic

2022-07-21 20:15 UTC, duca43 requested changes

2022-07-21 20:15 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +use App\Models\Image as ModelsImage;
Kul sto si upotrebio alis za to, samo je naming za ovo mogao biti mozda bolji, na primer ImageModel. Da, deluje maltene isto, ali ModelsImage je bas nekako weird, a i mnozina Models... A ako si isao na pripadnost, kao Model's, nije bas najjasnije.

Najbolja stvar ovde bi bila mozda da uradis obrnuto, da stavis alias za ovu `Image` fasadu koja dolazi iz lib-a. Posto je lib `Intervention`, ja bih isao sa:
```
use InterventionImage;
```

2022-07-21 20:15 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +        // =-=-=-=
👀

2022-07-21 20:15 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +        $url = $movieData['image_url'];
Po flow-u koji sam pisao na slacku, ovo ti ne treba.

2022-07-21 20:15 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +        $thumbnail = $path . "thumbnails/" . substr($url, strrpos($url, '/') + 1);
Posto nemas `$url` vise, najbolje je da na random generises naziv slike. To je nesto sto se radi zapravo.
```
Str::random(16); // 16 -> duzina generisanog stringa
```

2022-07-21 20:15 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +        $thumbnail = $path . "thumbnails/" . substr($url, strrpos($url, '/') + 1);
Neka obe slike imaju razlicit naziv na primer, dakle zasebno generises random string.
Druga opcija bi, na primer, bila da generises jedan string pa da se slike isto zovu, kad ih vec svakako cuvas u zasebnim folderima, pa bi se one na taj nacin lako razlikovale. Ovo je na tebi.

2022-07-21 20:15 UTC, duca43 commented on app/Http/Controllers/MovieController.php
>          $movie = Movie::create($movieData);
Ovo treba da uradis pre svega sto radis sa slikama.

2022-07-21 20:15 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +        $image['thumbnail'] = $thumbnail;
```
// Ako izmenis ono kako sam predlozio oko aliasa, onda Image::create...
ModelsImage::create([
     'full_size' => $name_full,
     'thumbnail' => $thumbnail,
     'movie_id' => $movie->id
];
```

2022-07-21 20:15 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +        $image['thumbnail'] = $thumbnail;
od 41. do 57. linije sve osim 54. linije bi trebalo biti izdvojeno u neku metodu servis klase, to sam pisao na slacku.

2022-07-21 20:15 UTC, duca43 commented on app/Models/Image.php
> +        'full-size',
Ovo je vec neka treca sintaksa, sa dash-om 😐 Moze ovde `full_size`.

2022-07-21 20:15 UTC, duca43 commented on database/migrations/2022_07_21_183634_create_image_table.php
> +            $table->string('full-size');
`full_size`

2022-07-22 09:13 UTC, duca43 requested changes
`public/uploads` folder bi trebalo da bude gitignore-ovan zapravo, jer zamisli da sve slike iz tog foldera guramo na repo.
Ispravi ovo sto sam pisao za putanje, ali i sve ono sto sam pisao na prvom commitu, sve ostalo nisi ispravio.

2022-07-22 09:13 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +        $name_thumb = public_path('uploads/movie/thumbnail/' . $image->getClientOriginalName());
<img width="793" alt="Screenshot 2022-07-22 at 11 08 15" src="https://user-images.githubusercontent.com/44477868/180405608-ec1ec046-373d-43b1-8311-3f33bcff58fa.png">

Na ovaj nacin, sacuvace se apsolutne putanje do fajlova, a to sam ti pisao na slacku da ne radimo, vec da cuvas samo relativne putanje, tj samo ono sto je promenljivo.

2022-07-22 09:17 UTC, NikolaVetnic commented on app/Http/Controllers/MovieController.php
> +use App\Models\Image as ModelsImage;
Uradjeno.

2022-07-22 09:17 UTC, NikolaVetnic commented on app/Http/Controllers/MovieController.php
> +        $url = $movieData['image_url'];
Ostavicu sebi za referencu, postoji onaj deo sa popunjavanjem podacima sa OMDBa, voleo bih da mi to ostane ako ubuduce nesto radio, da znam kako i sta.

2022-07-22 09:18 UTC, duca43 requested changes

2022-07-22 09:18 UTC, duca43 commented on app/Http/Controllers/MovieController.php
> +        Image::make($image->getContent())->resize(200, 200)->save($name_thumb);
Pisao si mi da ti ne radi ako stavis samo $image, ali evo ja sam kod sebe presao na ovu granu i probao bas bez poziva `getContent` funkcije i radi 🙂
<img width="879" alt="Screenshot 2022-07-22 at 11 18 29" src="https://user-images.githubusercontent.com/44477868/180407616-ea39c2ff-1e9e-4eb2-8713-a1e84fdb4a90.png">

2022-07-22 09:24 UTC, NikolaVetnic commented on app/Http/Controllers/MovieController.php
> +        $thumbnail = $path . "thumbnails/" . substr($url, strrpos($url, '/') + 1);
Uradjeno.

2022-07-22 09:33 UTC, NikolaVetnic commented on app/Http/Controllers/MovieController.php
> +        $image['thumbnail'] = $thumbnail;
Uradjeno.

2022-07-22 09:33 UTC, NikolaVetnic commented on app/Models/Image.php
> +        'full-size',
```Add an upload image field on the create movie form. The uploaded image should be resized (for full page & list page) and saved to disk into separate folders (/thumbnails & /full-size). Make thumbnails 200x200 and full-size 400x400 pixels.```
Tako pise u tasku...

2022-07-22 09:33 UTC, NikolaVetnic commented on database/migrations/2022_07_21_183634_create_image_table.php
> +            $table->string('full-size');
U tasku eksplicitno pise `full-size`.

2022-07-22 09:35 UTC, NikolaVetnic commented on app/Http/Controllers/MovieController.php
> +        $name_thumb = public_path('uploads/movie/thumbnail/' . $image->getClientOriginalName());
Stavio sam random generisanje stringova za ime, cuvaju se relativne putanje.

2022-07-22 09:39 UTC, NikolaVetnic commented on app/Http/Controllers/MovieController.php
> +        Image::make($image->getContent())->resize(200, 200)->save($name_thumb);
Sad i meni radi, ok.

2022-07-22 09:39 UTC, NikolaVetnic commented on database/migrations/2022_07_21_183634_create_image_table.php
> +            $table->string('full-size');
Reseno.

2022-07-22 09:39 UTC, NikolaVetnic commented on app/Http/Controllers/MovieController.php
>          $movie = Movie::create($movieData);
Uradjeno.

2022-07-22 12:41 UTC, duca43 approved these changes
Odlicno si ovo sad sredio, samo ovo oko ekstenzije sredi i moze merge.

2022-07-22 12:41 UTC, duca43 commented on app/Services/ImageService.php
> +        $ext = $temp[count($temp) - 1];
Postoji metoda u `UploadedFile` klasi da preuzmes ekstenziju iz fajla. Osim nje, postoji i metoda koja pokusava da provali koja je ekstenzija (na osnovu mime type-a, sadrzaja itd). U sustini bi mogao da koristis jednu od te dve, ali najbolje je imati kombinaciju zato sto ti nece uvek doci fajl koji ima zadatu ekstenziju. To nije cest slucaj, ali se moze desiti. Onda u tom slucaju zelimo da fallback-ujemo na to da on sam pretpostavi ekstenziju. Iz ove price, dolazimo do toga da bi neko dobro resenje (naravno ne idealno) bilo ovo:
```
$extension = $file->getClientOriginalExtension() ?: $file->guessExtension();
```

`?:` predstavlja skraceni ternarni operator, ne znam da li si do sada imao prilike to da vidis - specificno je za PHP. Vise o njemu [ovde](https://stitcher.io/blog/shorthand-comparisons-in-php#shorthand-ternary-operator).

2022-07-22 13:11 UTC, NikolaVetnic commented on app/Services/ImageService.php
> +        $ext = $temp[count($temp) - 1];
Sredjeno.

2022-07-22 13:16 UTC, merged