Register flow.
NikolaVetnic/VVF_Back pull request #2
Opened 2022-07-13 07:24 UTC by NikolaVetnic

2022-07-13 08:51 UTC, duca43 requested changes

2022-07-13 08:51 UTC, duca43 commented on app/Http/Controllers/AuthController.php
> +        $registerData = request(['name', 'email', 'password']);
Ovo je okej i ovo radi, ali mnogo cesce se radi na nacin da primas promenljivu koja je objekat klase `Request` (ili neke klase koja nasledjuje `Request` klasu i onda se podaci iz requesta vade iz te promenljive.
Nesto ovako:
```
public function register(Request $request)
{
    $registerData = $request->only(['name', 'email', 'password']);
```

2022-07-13 08:51 UTC, duca43 commented on app/Http/Controllers/AuthController.php
> +        $user->save();
Ovo sam ti vec pricao da nema potrebe da pravis prazan objekat Model (u ovom slucaju User) klase, vec mozes konstuktoru da prosledis niz sa podacima.
```
$user = new User($registerData);
```

2022-07-13 08:51 UTC, duca43 commented on app/Http/Controllers/RegisterController.php
> +    }
Ako vec ovo radis u AuthController-u, kontam ovo ti ne treba. Verujem da si ovo koristio samo da nesto isprobas, ali onda takve stvari i uklonis iz koda ako se ne koriste zaista.

2022-07-13 08:51 UTC, duca43 commented on routes/api.php
> +// Route::post('/auth/register', [RegisterController::class, 'register']);
Isto kao komentar iznad.

2022-07-13 08:52 UTC, duca43 approved these changes

2022-07-14 10:43 UTC, NikolaVetnic commented on app/Http/Controllers/AuthController.php
> +        $registerData = request(['name', 'email', 'password']);
Sredio:```    public function register(Request $request)
    {
        $registerData = $request->only(['name', 'email', 'password']);

        $existingUser = User::where('email', $registerData['email'])->first();

        if ($existingUser != null)
            return response()->json(['message' => 'Email already taken']);

        $registerData['password'] = Hash::make($registerData['password']);

        $user = User::create($registerData);

        return $user;
    }```

2022-07-14 10:44 UTC, NikolaVetnic commented on app/Http/Controllers/AuthController.php
> +        $user->save();
Sredjeno, komentar iznad.

2022-07-14 10:44 UTC, duca43 commented on app/Http/Controllers/AuthController.php
> +        $registerData = request(['name', 'email', 'password']);
👀 
```
if ($existingUser != null) {
    return response()->json(['message' => 'Email already taken']);
}
```

2022-07-14 10:45 UTC, NikolaVetnic commented on app/Http/Controllers/RegisterController.php
> +    }
Obrisao, to je bilo neko testiranje nesto, zaboravih da sklonim.

2022-07-14 10:45 UTC, NikolaVetnic commented on app/Http/Controllers/AuthController.php
> +            return response()->json(['message' => 'Email already taken']);
:'( Resio...

2022-07-14 10:46 UTC, NikolaVetnic commented on app/Http/Controllers/AuthController.php
> +        if ($existingUser != null)
Dogovoreno, uradjeno.

2022-07-14 11:39 UTC, duca43 approved these changes

2022-07-14 12:59 UTC, merged